const WHATSAPP='5545991469037';
const WA_ICON='';
function waUrl(message){return `https://wa.me/${WHATSAPP}?text=${encodeURIComponent(message)}`}
function setupMenu(){const t=document.querySelector('.mobile-toggle');const n=document.querySelector('.nav-links');if(t&&n)t.addEventListener('click',()=>n.classList.toggle('open'))}
function setupHero(){const slides=[...document.querySelectorAll('.hero-slide')],dots=[...document.querySelectorAll('.hero-dot')];if(!slides.length)return;let i=0;const show=n=>{slides.forEach((s,x)=>s.classList.toggle('active',x===n));dots.forEach((d,x)=>d.classList.toggle('active',x===n));i=n};dots.forEach((d,x)=>d.onclick=()=>show(x));setInterval(()=>show((i+1)%slides.length),5000)}
function card(item,type='passeio'){
 const isHotel=type==='hotel'; const isTicket=type==='ingresso'||type==='evento';
 const price=isHotel?'':isTicket?`<div class="price"><small>${item.preco||'Valores a partir de'}</small>${item.valor||'Consulte'}</div>`:`<div class="price">${item.preco||'Preço sob consulta'}</div>`;
 const detailHref=`detalhes.html?tipo=${type}&id=${item.id}`;
 const action=isHotel?`<div class="hotel-contact"><a class="btn btn-outline" target="_blank" rel="noopener" href="${item.contato||'#'}">Contato do hotel</a></div>`:`<a class="card-link" href="${detailHref}"><span>Mais detalhes</span><span>›</span></a>`;
 return `<article class="card"><a class="card-media" href="${isHotel?(item.contato||'#'):detailHref}" ${isHotel?'target="_blank" rel="noopener"':''}>${item.destaque?'<span class="rec-badge">Indicação da semana</span>':''}<img src="${item.imagem}" alt="${item.nome}" loading="lazy"></a><div class="card-body"><span class="tag">${item.categoria}</span><h3>${item.nome}</h3><p>${item.resumo}</p>${price}${action}</div></article>`
}
function renderCards(selector,items,type='passeio',limit){const el=document.querySelector(selector);if(!el)return;const list=limit?items.slice(0,limit):items;el.innerHTML=list.map(x=>card(x,type)).join('')}
function setupFilters(items,type){const grid=document.querySelector('#catalog-grid');if(!grid)return;const buttons=[...document.querySelectorAll('.filter-btn')],select=document.querySelector('#catalog-select'),search=document.querySelector('#catalog-search');let current='Todos';let query='';const render=()=>{let list=current==='Todos'?items:items.filter(x=>x.categoria===current);if(query){const n=query.toLowerCase();list=list.filter(x=>`${x.nome} ${x.categoria} ${x.local||''} ${x.resumo||''}`.toLowerCase().includes(n))}grid.innerHTML=list.length?list.map(x=>card(x,type)).join(''):'<p class="muted">Nenhum resultado encontrado.</p>'};buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');current=b.dataset.filter;if(select)select.value=current;render()}));if(select)select.addEventListener('change',()=>{current=select.value;buttons.forEach(x=>x.classList.toggle('active',x.dataset.filter===current));render()});if(search)search.addEventListener('input',()=>{query=search.value.trim();render()});render()}
function fillHome(){if(!window.CARINE_DATA)return;renderCards('#featured-passeios',CARINE_DATA.passeios,'passeio',6);renderCards('#featured-ingressos',CARINE_DATA.ingressos,'ingresso',3)}
function setupSearch(){const input=document.querySelector('#home-search');if(!input)return;const btn=document.querySelector('#home-search-btn');const go=()=>{const q=input.value.trim();location.href=`passeios.html${q?`?q=${encodeURIComponent(q)}`:''}`};btn?.addEventListener('click',go);input.addEventListener('keydown',e=>{if(e.key==='Enter')go()})}
function renderFooter(){const footer=document.querySelector('[data-footer]');if(!footer)return;footer.className='footer';footer.innerHTML=`<div class="container"><div class="footer-grid"><div><a class="brand footer-brand" href="index.html"><img src="assets/logo/favicon-carine.png" alt="Carine Turismo"><span>CARINE TURISMO</span></a><p>Transporte turístico, passeios e ingressos em Foz do Iguaçu e na tríplice fronteira.</p></div><div><h4>Explore</h4><div class="footer-links"><a href="passeios.html">Passeios</a><a href="transporte.html">Transporte</a><a href="ingressos.html">Ingressos</a></div></div><div><h4>Outros</h4><div class="footer-links"><a href="hoteis.html">Hotéis</a><a href="eventos.html">Eventos</a><a href="index.html#sobre">Sobre a Carine</a></div></div><div><h4>Contato</h4><div class="footer-links"><a target="_blank" href="https://wa.me/${WHATSAPP}">(45) 99146-9037</a><a target="_blank" href="https://instagram.com/carine.turimo">@carine.turimo</a><span style="color:rgba(255,255,255,.72)">CNPJ 53.729.747/0001-41</span></div></div></div><div class="footer-bottom">© 2026 Carine Turismo. Site catálogo — valores e disponibilidade sujeitos a consulta.</div></div>`}
function renderWhatsapp(){document.querySelectorAll('.whatsapp-float').forEach(a=>{a.innerHTML='<span class="wa-mark" aria-hidden="true"><svg viewBox="0 0 32 32" role="img"><path fill="currentColor" d="M19.11 17.38c-.27-.14-1.6-.79-1.85-.88-.25-.09-.43-.14-.61.14-.18.27-.7.88-.86 1.06-.16.18-.32.2-.59.07-.27-.14-1.15-.42-2.19-1.35-.81-.72-1.36-1.61-1.52-1.88-.16-.27-.02-.42.12-.55.12-.12.27-.32.41-.48.14-.16.18-.27.27-.45.09-.18.05-.34-.02-.48-.07-.14-.61-1.47-.84-2.01-.22-.53-.45-.46-.61-.47h-.52c-.18 0-.48.07-.73.34-.25.27-.95.93-.95 2.27s.98 2.63 1.11 2.81c.14.18 1.92 2.93 4.65 4.11.65.28 1.16.45 1.55.58.65.21 1.24.18 1.71.11.52-.08 1.6-.65 1.83-1.29.23-.63.23-1.18.16-1.29-.07-.11-.25-.18-.52-.32z"/><path fill="currentColor" d="M16.04 3C8.86 3 3.02 8.83 3.02 16c0 2.29.6 4.53 1.73 6.5L3 29l6.67-1.75A12.96 12.96 0 0 0 16.04 29C23.22 29 29 23.17 29 16S23.22 3 16.04 3zm0 23.81c-2.05 0-4.05-.55-5.79-1.58l-.42-.25-3.96 1.04 1.06-3.86-.27-.43A10.75 10.75 0 0 1 5.2 16c0-5.98 4.86-10.82 10.84-10.82 5.97 0 10.79 4.84 10.79 10.82 0 5.97-4.82 10.81-10.79 10.81z"/></svg></span>';a.href=waUrl(a.dataset.wa||'Olá! Gostaria de falar com a Carine Turismo.')})}
document.addEventListener('DOMContentLoaded',async()=>{if(window.CARINE_DATA_READY)await window.CARINE_DATA_READY;setupMenu();setupHero();fillHome();setupSearch();renderFooter();document.querySelectorAll('[data-wa]').forEach(a=>a.href=waUrl(a.dataset.wa||'Olá! Gostaria de solicitar um orçamento com a Carine Turismo.'));renderWhatsapp();document.dispatchEvent(new Event('carine:data-ready'))})
