-- CARINE TURISMO — estrutura final do painel
-- Pode executar este arquivo inteiro no SQL Editor do Supabase.

create table if not exists public.catalogo (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('passeio','ingresso','hotel','evento')),
  dados jsonb not null default '{}'::jsonb,
  ordem integer not null default 999,
  created_at timestamptz not null default now()
);
alter table public.catalogo enable row level security;

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  nome text not null,
  tipo text not null default 'passeio' check (tipo in ('passeio','ingresso','hotel','evento')),
  imagem text not null default '',
  resumo text not null default '',
  ordem integer not null default 999,
  home boolean not null default false,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.categorias enable row level security;

create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  imagem text not null,
  destaque text not null default '',
  titulo text not null,
  texto text not null default '',
  botao_texto text not null default '',
  botao_link text not null default '',
  ordem integer not null default 999,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.banners enable row level security;

insert into public.categorias (slug,nome,tipo,imagem,resumo,ordem,home,ativo) values
('foz-do-iguacu','Foz do Iguaçu','passeio','https://imgcdn.bokun.tools/360afe49-e312-4e1c-b095-ab0873b2661d.jpeg','Cataratas, Itaipu, Parque das Aves, AquaFoz e muito mais.',10,true,true),
('paraguai','Paraguai','passeio','assets/images/paraguai-home.png','Compras em Ciudad del Este com ida e retorno combinados.',20,true,true),
('argentina','Argentina','passeio','assets/images/argentina-home.png','Feirinha, Cataratas Argentinas e experiências em Puerto Iguazú.',30,true,true),
('foz-ingressos','Foz do Iguaçu','ingresso','', 'Ingressos e experiências em Foz do Iguaçu.',10,false,true),
('eventos','Eventos','evento','', 'Eventos e experiências por temporada.',10,false,true),
('centro','Centro','hotel','', 'Hotéis na região central de Foz.',10,false,true),
('rodovia-cataratas','Rodovia das Cataratas','hotel','', 'Hotéis e resorts na região da Rodovia das Cataratas.',20,false,true)
on conflict (slug) do update set nome=excluded.nome,tipo=excluded.tipo,imagem=excluded.imagem,resumo=excluded.resumo,ordem=excluded.ordem,home=excluded.home,ativo=excluded.ativo;

insert into public.banners (slug,imagem,destaque,titulo,texto,botao_texto,botao_link,ordem,ativo) values
('cataratas','https://imgcdn.bokun.tools/360afe49-e312-4e1c-b095-ab0873b2661d.jpeg','CATARATAS DO IGUAÇU','Foz do Iguaçu começa por aqui.','Transporte particular para os principais atrativos, com ida e busca combinadas para você aproveitar o passeio no seu ritmo.','Explorar passeios','passeios.html',10,true),
('itaipu','https://www.adibra.com.br/Content/upload/photos/2723/turistas-2.jpg','ITAIPU BINACIONAL','Conheça os ícones de Foz com conforto.','Você escolhe o roteiro e a Carine cuida do deslocamento até o atrativo e da busca combinada.','Ver detalhes','detalhes.html?tipo=passeio&id=itaipu',20,true),
('macuco-safari','https://media.tacdn.com/media/attractions-splice-spp-210x118/07/90/b5/22.jpg','MACUCO SAFARI','Aventura também entra no roteiro.','Transporte até o Parque Nacional do Iguaçu para quem quer viver o Macuco Safari.','Conhecer opção','detalhes.html?tipo=passeio&id=macuco-safari',30,true),
('parque-das-aves','https://www.tangol.com/Blog/Fotos/parque-das-aves-birds-park-at-exuberant-iguazu-forest_0_201805231437130-resized.webp','PARQUE DAS AVES','Natureza, praticidade e um roteiro leve.','Combine Parque das Aves, Cataratas e outros pontos próximos no seu dia.','Ver detalhes','detalhes.html?tipo=passeio&id=parque-das-aves',40,true)
on conflict (slug) do update set imagem=excluded.imagem,destaque=excluded.destaque,titulo=excluded.titulo,texto=excluded.texto,botao_texto=excluded.botao_texto,botao_link=excluded.botao_link,ordem=excluded.ordem,ativo=excluded.ativo;

-- Importa itens-base para que também possam ser editados/apagados pelo painel.
insert into public.catalogo (tipo,dados,ordem) select 'passeio','{"id":"cataratas-brasil","nome":"Cataratas do Iguaçu","categoria":"Foz do Iguaçu","local":"Parque Nacional do Iguaçu","preco":"Preço sob consulta","destaque":true,"imagem":"https://imgcdn.bokun.tools/360afe49-e312-4e1c-b095-ab0873b2661d.jpeg","resumo":"Ida até o Parque Nacional do Iguaçu e busca em horário combinado.","descricao":"Conheça as Cataratas do Iguaçu com a tranquilidade de ter o transporte organizado.","inclui":["Transporte até o atrativo","Busca em horário combinado","Atendimento direto pelo WhatsApp"],"observacao":"Serviço de transporte. Não inclui acompanhamento de guia turístico nem ingresso da atração."}'::jsonb,10 where not exists(select 1 from public.catalogo where tipo='passeio' and dados->>'id'='cataratas-brasil');
insert into public.catalogo (tipo,dados,ordem) select 'passeio','{"id":"itaipu","nome":"Itaipu Binacional","categoria":"Foz do Iguaçu","local":"Complexo Turístico Itaipu","preco":"Preço sob consulta","destaque":true,"imagem":"https://www.adibra.com.br/Content/upload/photos/2723/turistas-2.jpg","resumo":"Transporte para conhecer o complexo turístico da Itaipu Binacional."}'::jsonb,20 where not exists(select 1 from public.catalogo where tipo='passeio' and dados->>'id'='itaipu');
insert into public.catalogo (tipo,dados,ordem) select 'passeio','{"id":"parque-das-aves","nome":"Parque das Aves","categoria":"Foz do Iguaçu","local":"Rodovia das Cataratas","preco":"Preço sob consulta","destaque":true,"imagem":"https://www.tangol.com/Blog/Fotos/parque-das-aves-birds-park-at-exuberant-iguazu-forest_0_201805231437130-resized.webp","resumo":"Transporte até o Parque das Aves, próximo às Cataratas."}'::jsonb,30 where not exists(select 1 from public.catalogo where tipo='passeio' and dados->>'id'='parque-das-aves');
insert into public.catalogo (tipo,dados,ordem) select 'passeio','{"id":"macuco-safari","nome":"Macuco Safari","categoria":"Foz do Iguaçu","local":"Parque Nacional do Iguaçu","preco":"Preço sob consulta","destaque":true,"imagem":"https://media.tacdn.com/media/attractions-splice-spp-210x118/07/90/b5/22.jpg","resumo":"Transporte até o Parque Nacional para quem vai viver a experiência Macuco Safari."}'::jsonb,40 where not exists(select 1 from public.catalogo where tipo='passeio' and dados->>'id'='macuco-safari');
insert into public.catalogo (tipo,dados,ordem) select 'passeio','{"id":"aquafoz","nome":"AquaFoz","categoria":"Foz do Iguaçu","local":"Rodovia das Cataratas","preco":"Preço sob consulta","imagem":"https://media.gazetadopovo.com.br/2025/11/14104540/AquaFoz-Kiko-Sierich-7.jpg.webp","resumo":"Transporte para o AquaFoz com ida e busca combinadas."}'::jsonb,50 where not exists(select 1 from public.catalogo where tipo='passeio' and dados->>'id'='aquafoz');
insert into public.catalogo (tipo,dados,ordem) select 'passeio','{"id":"templo-budista","nome":"Templo Budista Chen Tien","categoria":"Foz do Iguaçu","local":"Foz do Iguaçu","preco":"Preço sob consulta","imagem":"https://portaldafronteira.com/storage/2020/08/FozdoIguacuTemploBudista_002-1137x800.jpg","resumo":"Transporte para uma visita tranquila ao Templo Budista de Foz."}'::jsonb,60 where not exists(select 1 from public.catalogo where tipo='passeio' and dados->>'id'='templo-budista');
insert into public.catalogo (tipo,dados,ordem) select 'passeio','{"id":"marco-tres-fronteiras","nome":"Marco das Três Fronteiras","categoria":"Foz do Iguaçu","local":"Foz do Iguaçu","preco":"Preço sob consulta","imagem":"https://destinobrasilte.com.br/wp-content/uploads/2021/05/marco-das-tres-fronteiras-deve-bater-a-marca-de-1-milhao-de-visitantes-5d59cbb15135f.jpg","resumo":"Transporte até um dos lugares mais simbólicos da tríplice fronteira."}'::jsonb,70 where not exists(select 1 from public.catalogo where tipo='passeio' and dados->>'id'='marco-tres-fronteiras');
insert into public.catalogo (tipo,dados,ordem) select 'passeio','{"id":"movie-cars","nome":"Movie Cars","categoria":"Foz do Iguaçu","local":"Wonder Park Foz","preco":"Preço sob consulta","imagem":"https://www.hoteldelreyfoz.com.br/wp-content/uploads/2021/01/1-Imagem-Movie-Cars-Entertainment-scaled-1.jpg","resumo":"Transporte para o Movie Cars em Foz do Iguaçu."}'::jsonb,80 where not exists(select 1 from public.catalogo where tipo='passeio' and dados->>'id'='movie-cars');
insert into public.catalogo (tipo,dados,ordem) select 'passeio','{"id":"compras-paraguai","nome":"Compras no Paraguai","categoria":"Paraguai","local":"Ciudad del Este","preco":"Preço sob consulta","imagem":"https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/07/9d/76/5d.jpg","resumo":"Transporte para compras em Ciudad del Este com retorno combinado."}'::jsonb,90 where not exists(select 1 from public.catalogo where tipo='passeio' and dados->>'id'='compras-paraguai');
insert into public.catalogo (tipo,dados,ordem) select 'passeio','{"id":"feirinha-argentina","nome":"Feirinha de Puerto Iguazú","categoria":"Argentina","local":"Puerto Iguazú","preco":"Preço sob consulta","imagem":"https://mindtrip.ai/attractions/8634/db03/0686/0f67/3185/e9ff/5464/5388","resumo":"Transporte até a tradicional Feirinha de Puerto Iguazú."}'::jsonb,100 where not exists(select 1 from public.catalogo where tipo='passeio' and dados->>'id'='feirinha-argentina');
insert into public.catalogo (tipo,dados,ordem) select 'passeio','{"id":"cataratas-argentina","nome":"Cataratas Argentinas","categoria":"Argentina","local":"Parque Nacional Iguazú","preco":"Preço sob consulta","imagem":"https://cdn.getyourguide.com/image/format=auto,fit=crop,gravity=auto,quality=60,width=450,height=450,dpr=2/tour_img/5cd1d7a0d3197.jpeg","resumo":"Transporte para o lado argentino das Cataratas."}'::jsonb,110 where not exists(select 1 from public.catalogo where tipo='passeio' and dados->>'id'='cataratas-argentina');
insert into public.catalogo (tipo,dados,ordem) select 'passeio','{"id":"oda-argentina","nome":"ODA Argentina","categoria":"Argentina","local":"Puerto Iguazú","preco":"Preço sob consulta","imagem":"https://neumanntour.com.br/wp-content/gallery/oda_vinoteca/foto-3.jpg","resumo":"Transporte até a ODA Vinoteca em Puerto Iguazú."}'::jsonb,120 where not exists(select 1 from public.catalogo where tipo='passeio' and dados->>'id'='oda-argentina');
insert into public.catalogo (tipo,dados,ordem) select 'passeio','{"id":"oda-duty-free","nome":"ODA Duty Free Foz","categoria":"Foz do Iguaçu","local":"Vila Yolanda","preco":"Preço sob consulta","imagem":"https://www.iguassu.com.br/wp-content/uploads/2022/06/Oda-Vinoteca-3-1536x1024.jpg","resumo":"Transporte para a ODA Duty Free em Foz do Iguaçu."}'::jsonb,130 where not exists(select 1 from public.catalogo where tipo='passeio' and dados->>'id'='oda-duty-free');
insert into public.catalogo (tipo,dados,ordem) select 'ingresso','{"id":"ingresso-cataratas","nome":"Ingresso Cataratas do Iguaçu","categoria":"Foz do Iguaçu","local":"Parque Nacional do Iguaçu","preco":"Valores a partir de","valor":"Consulte","imagem":"https://imgcdn.bokun.tools/360afe49-e312-4e1c-b095-ab0873b2661d.jpeg","resumo":"Consulte disponibilidade e valores atualizados pelo WhatsApp."}'::jsonb,140 where not exists(select 1 from public.catalogo where tipo='ingresso' and dados->>'id'='ingresso-cataratas');
insert into public.catalogo (tipo,dados,ordem) select 'ingresso','{"id":"ingresso-parque-aves","nome":"Ingresso Parque das Aves","categoria":"Foz do Iguaçu","local":"Parque das Aves","preco":"Valores a partir de","valor":"Consulte","imagem":"https://www.tangol.com/Blog/Fotos/parque-das-aves-birds-park-at-exuberant-iguazu-forest_0_201805231437130-resized.webp","resumo":"Consulte disponibilidade e valores atualizados pelo WhatsApp."}'::jsonb,150 where not exists(select 1 from public.catalogo where tipo='ingresso' and dados->>'id'='ingresso-parque-aves');
insert into public.catalogo (tipo,dados,ordem) select 'ingresso','{"id":"ingresso-macuco","nome":"Ingresso Macuco Safari","categoria":"Foz do Iguaçu","local":"Parque Nacional do Iguaçu","preco":"Valores a partir de","valor":"Consulte","imagem":"https://media.tacdn.com/media/attractions-splice-spp-210x118/07/90/b5/22.jpg","resumo":"Consulte disponibilidade e valores atualizados pelo WhatsApp."}'::jsonb,160 where not exists(select 1 from public.catalogo where tipo='ingresso' and dados->>'id'='ingresso-macuco');
insert into public.catalogo (tipo,dados,ordem) select 'ingresso','{"id":"ingresso-aquafoz","nome":"Ingresso AquaFoz","categoria":"Foz do Iguaçu","local":"AquaFoz","preco":"Valores a partir de","valor":"Consulte","imagem":"https://media.gazetadopovo.com.br/2025/11/14104540/AquaFoz-Kiko-Sierich-7.jpg.webp","resumo":"Consulte disponibilidade e valores atualizados pelo WhatsApp."}'::jsonb,170 where not exists(select 1 from public.catalogo where tipo='ingresso' and dados->>'id'='ingresso-aquafoz');
insert into public.catalogo (tipo,dados,ordem) select 'ingresso','{"id":"ingresso-movie-cars","nome":"Ingresso Movie Cars","categoria":"Foz do Iguaçu","local":"Wonder Park Foz","preco":"Valores a partir de","valor":"Consulte","imagem":"https://www.hoteldelreyfoz.com.br/wp-content/uploads/2021/01/1-Imagem-Movie-Cars-Entertainment-scaled-1.jpg","resumo":"Consulte disponibilidade e valores atualizados pelo WhatsApp."}'::jsonb,180 where not exists(select 1 from public.catalogo where tipo='ingresso' and dados->>'id'='ingresso-movie-cars');
insert into public.catalogo (tipo,dados,ordem) select 'hotel','{"id":"hotel-1","nome":"Hotel em Foz do Iguaçu","categoria":"Centro","local":"Foz do Iguaçu","imagem":"https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=88","resumo":"Sugestão de hospedagem para incluir no seu planejamento.","contato":"#"}'::jsonb,190 where not exists(select 1 from public.catalogo where tipo='hotel' and dados->>'id'='hotel-1');
insert into public.catalogo (tipo,dados,ordem) select 'hotel','{"id":"hotel-2","nome":"Resort em Foz do Iguaçu","categoria":"Rodovia das Cataratas","local":"Foz do Iguaçu","imagem":"https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1400&q=88","resumo":"Opção de resort para famílias e casais.","contato":"#"}'::jsonb,200 where not exists(select 1 from public.catalogo where tipo='hotel' and dados->>'id'='hotel-2');
insert into public.catalogo (tipo,dados,ordem) select 'evento','{"id":"evento-exemplo","nome":"Eventos em Foz do Iguaçu","categoria":"Eventos","local":"Foz do Iguaçu","preco":"Valores a partir de","valor":"Consulte","imagem":"https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1400&q=88","resumo":"Shows, experiências e eventos especiais disponíveis por temporada."}'::jsonb,210 where not exists(select 1 from public.catalogo where tipo='evento' and dados->>'id'='evento-exemplo');

-- Não crie policies públicas de escrita. O Vercel acessa usando a chave secreta no servidor.
