create table if not exists public.catalogo (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('passeio','ingresso','hotel','evento')),
  dados jsonb not null default '{}'::jsonb,
  ordem integer not null default 999,
  created_at timestamptz not null default now()
);

alter table public.catalogo enable row level security;
-- O site público lê por uma função server-side do Vercel usando service role.
-- Não crie policy pública de escrita.
