const $=s=>document.querySelector(s);let rows=[];const login=$('#login'),panel=$('#panel'),form=$('#item-form'),msg=$('#form-msg');
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Erro na solicitação');return data}
async function load(){try{rows=await api('/api/admin-list');login.hidden=true;panel.hidden=false;render()}catch{login.hidden=false;panel.hidden=true}}
function render(){$('#items').innerHTML=rows.length?rows.map(r=>`<div class="admin-item"><div><b>${esc(r.dados?.nome||'Sem nome')}</b><br><small>${esc(r.tipo)} · ${esc(r.dados?.categoria||'')}</small></div><div class="admin-item-actions"><button class="mini" data-edit="${r.id}">Editar</button><button class="mini danger" data-del="${r.id}">Excluir</button></div></div>`).join(''):'<p>Nenhum item cadastrado no banco.</p>'}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#login-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('/api/login',{method:'POST',body:JSON.stringify({user:f.get('user'),password:f.get('password')})});$('#login-msg').textContent='';load()}catch(err){$('#login-msg').textContent=err.message}};
form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form);const nome=f.get('nome').trim();const dados={id:nome.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),nome,categoria:f.get('categoria').trim(),local:f.get('local').trim(),imagem:f.get('imagem').trim(),resumo:f.get('resumo').trim(),descricao:f.get('descricao').trim(),preco:f.get('preco').trim(),valor:f.get('valor').trim(),destaque:f.get('destaque')==='on',inclui:f.get('inclui').split('\n').map(x=>x.trim()).filter(Boolean),observacao:f.get('observacao').trim(),contato:f.get('contato').trim()};const dbid=f.get('dbid');try{await api('/api/catalog',{method:dbid?'PUT':'POST',body:JSON.stringify({id:dbid,tipo:f.get('tipo'),ordem:f.get('ordem'),dados})});msg.textContent='Salvo com sucesso.';clear();await load()}catch(err){msg.textContent=err.message}};
$('#items').onclick=async e=>{const id=e.target.dataset.edit||e.target.dataset.del;if(!id)return;const r=rows.find(x=>String(x.id)===String(id));if(e.target.dataset.edit){const d=r.dados||{};for(const [k,v] of Object.entries({dbid:r.id,tipo:r.tipo,ordem:r.ordem||999,...d,inclui:(d.inclui||[]).join('\n')})){const el=form.elements[k];if(!el)continue;if(el.type==='checkbox')el.checked=!!v;else el.value=v??''}$('#form-title').textContent='Editar item';scrollTo({top:0,behavior:'smooth'})}else if(confirm(`Excluir “${r.dados?.nome}”?`)){await api('/api/catalog',{method:'DELETE',body:JSON.stringify({id:r.id})});await load()}};
function clear(){form.reset();form.elements.dbid.value='';form.elements.preco.value='Preço sob consulta';form.elements.ordem.value='999';$('#form-title').textContent='Adicionar item'}$('#cancel-edit').onclick=clear;$('#refresh').onclick=load;$('#logout').onclick=async()=>{await api('/api/logout',{method:'POST'});location.reload()};load();
