const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let rows=[],site={categorias:[],banners:[]};
const itemForm=$('#item-form'),categoryForm=$('#category-form'),bannerForm=$('#banner-form');
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function slugify(v=''){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},cache:'no-store',...opt});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Erro na solicitação');return data}
async function load(){try{const [catalog,config]=await Promise.all([api('/api/admin-list'),api('/api/site-admin')]);rows=catalog||[];site=config||{categorias:[],banners:[]};renderAll();return true}catch(err){if(/Não autorizado/i.test(err.message)){location.replace('/admin/');return false}alert('O painel não carregou: '+err.message);return false}}
function adminImg(src=''){return /^(https?:|data:|\/)/i.test(src)?src:'/'+src.replace(/^\.\//,'')}
function thumb(src,name){return src?`<img class="admin-thumb" src="${esc(adminImg(src))}" alt="${esc(name)}">`:''}
function renderItems(){const filter=$('#item-type-filter').value;const list=filter==='todos'?rows:rows.filter(r=>r.tipo===filter);$('#items').innerHTML=list.length?list.map(r=>`<div class="admin-item ${r.dados?.imagem?'':'no-thumb'}">${thumb(r.dados?.imagem,r.dados?.nome)}<div><b>${esc(r.dados?.nome||'Sem nome')}</b><br><small>${esc(r.tipo)} · ${esc(r.dados?.categoria||'Sem categoria')}</small></div><div class="admin-item-actions"><button class="mini" data-kind="item" data-edit="${r.id}">Editar</button><button class="mini danger" data-kind="item" data-del="${r.id}">Excluir</button></div></div>`).join(''):'<p>Nenhum conteúdo cadastrado.</p>'}
function renderCategories(){const arr=site.categorias||[];$('#categories').innerHTML=arr.length?arr.map(c=>`<div class="admin-item ${c.imagem?'':'no-thumb'}">${thumb(c.imagem,c.nome)}<div><b>${esc(c.nome)}</b>${c.home?'<span class="status-pill">Home</span>':''}${c.ativo===false?'<span class="status-pill off">Inativa</span>':''}<br><small>${esc(c.tipo)} · ordem ${esc(c.ordem)}</small></div><div class="admin-item-actions"><button class="mini" data-kind="category" data-edit="${c.id}">Editar</button><button class="mini danger" data-kind="category" data-del="${c.id}">Excluir</button></div></div>`).join(''):'<p>Nenhuma categoria cadastrada.</p>'}
function renderBanners(){const arr=site.banners||[];$('#banners').innerHTML=arr.length?arr.map(b=>`<div class="admin-item ${b.imagem?'':'no-thumb'}">${thumb(b.imagem,b.titulo)}<div><b>${esc(b.titulo)}</b>${b.ativo===false?'<span class="status-pill off">Inativo</span>':''}<br><small>${esc(b.destaque||b.slug)} · ordem ${esc(b.ordem)}</small></div><div class="admin-item-actions"><button class="mini" data-kind="banner" data-edit="${b.id}">Editar</button><button class="mini danger" data-kind="banner" data-del="${b.id}">Excluir</button></div></div>`).join(''):'<p>Nenhum banner cadastrado.</p>'}
function fillDatalist(){const type=itemForm.elements.tipo.value;const cats=(site.categorias||[]).filter(c=>c.ativo!==false&&c.tipo===type).map(c=>c.nome);$('#category-options').innerHTML=cats.map(c=>`<option value="${esc(c)}"></option>`).join('')}
function renderAll(){renderItems();renderCategories();renderBanners();fillDatalist()}
$$('.admin-tab').forEach(btn=>btn.onclick=()=>{$$('.admin-tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector(`[data-panel="${btn.dataset.tab}"]`).classList.add('active')});
itemForm.elements.tipo.onchange=fillDatalist;
itemForm.onsubmit=async e=>{e.preventDefault();const f=new FormData(itemForm),nome=f.get('nome').trim();const dados={id:slugify(nome),nome,categoria:f.get('categoria').trim(),local:f.get('local').trim(),imagem:f.get('imagem').trim(),galeria:f.get('galeria').split('\n').map(x=>x.trim()).filter(Boolean),resumo:f.get('resumo').trim(),descricao:f.get('descricao').trim(),preco:f.get('preco').trim(),valor:f.get('valor').trim(),destaque:f.get('destaque')==='on',inclui:f.get('inclui').split('\n').map(x=>x.trim()).filter(Boolean),observacao:f.get('observacao').trim(),contato:f.get('contato').trim()};const dbid=f.get('dbid');try{await api('/api/catalog',{method:dbid?'PUT':'POST',body:JSON.stringify({id:dbid,tipo:f.get('tipo'),ordem:Number(f.get('ordem')||999),dados})});$('#form-msg').textContent='Salvo com sucesso.';clearItem();await load()}catch(err){if(/Não autorizado/i.test(err.message))return location.replace('/admin/');$('#form-msg').textContent=err.message}};
categoryForm.onsubmit=async e=>{e.preventDefault();const f=new FormData(categoryForm),nome=f.get('nome').trim();const data={tipo:f.get('tipo'),nome,slug:f.get('slug').trim()||slugify(nome),imagem:f.get('imagem').trim(),resumo:f.get('resumo').trim(),ordem:Number(f.get('ordem')||999),home:f.get('home')==='on',ativo:f.get('ativo')==='on'};const id=f.get('dbid');try{await api('/api/site-admin',{method:id?'PUT':'POST',body:JSON.stringify({resource:'categoria',id,data})});$('#category-msg').textContent='Categoria salva.';clearCategory();await load()}catch(err){if(/Não autorizado/i.test(err.message))return location.replace('/admin/');$('#category-msg').textContent=err.message}};
bannerForm.onsubmit=async e=>{e.preventDefault();const f=new FormData(bannerForm),titulo=f.get('titulo').trim();const data={slug:f.get('slug').trim()||slugify(titulo),imagem:f.get('imagem').trim(),destaque:f.get('destaque').trim(),titulo,texto:f.get('texto').trim(),botao_texto:f.get('botao_texto').trim(),botao_link:f.get('botao_link').trim(),ordem:Number(f.get('ordem')||999),ativo:f.get('ativo')==='on'};const id=f.get('dbid');try{await api('/api/site-admin',{method:id?'PUT':'POST',body:JSON.stringify({resource:'banner',id,data})});$('#banner-msg').textContent='Banner salvo.';clearBanner();await load()}catch(err){if(/Não autorizado/i.test(err.message))return location.replace('/admin/');$('#banner-msg').textContent=err.message}};
function clearItem(){itemForm.reset();itemForm.elements.dbid.value='';itemForm.elements.preco.value='Preço sob consulta';itemForm.elements.ordem.value='999';$('#form-title').textContent='Adicionar conteúdo';fillDatalist()}
function clearCategory(){categoryForm.reset();categoryForm.elements.dbid.value='';categoryForm.elements.ordem.value='999';categoryForm.elements.ativo.checked=true;$('#category-title').textContent='Adicionar categoria'}
function clearBanner(){bannerForm.reset();bannerForm.elements.dbid.value='';bannerForm.elements.ordem.value='999';bannerForm.elements.ativo.checked=true;$('#banner-title').textContent='Adicionar banner'}
$('#cancel-edit').onclick=clearItem;$('#cancel-category').onclick=clearCategory;$('#cancel-banner').onclick=clearBanner;$('#refresh').onclick=load;$('#item-type-filter').onchange=renderItems;$('#logout').onclick=async()=>{try{await api('/api/logout',{method:'POST'})}finally{location.replace('/admin/')}};
function handleEdit(kind,id){if(kind==='item'){const r=rows.find(x=>String(x.id)===String(id));if(!r)return;const d=r.dados||{};for(const [k,v] of Object.entries({dbid:r.id,tipo:r.tipo,ordem:r.ordem||999,...d,galeria:(d.galeria||[]).join('\n'),inclui:(d.inclui||[]).join('\n')})){const el=itemForm.elements[k];if(!el)continue;if(el.type==='checkbox')el.checked=!!v;else el.value=v??''}$('#form-title').textContent='Editar conteúdo';fillDatalist();window.scrollTo({top:0,behavior:'smooth'});return}if(kind==='category'){const c=(site.categorias||[]).find(x=>String(x.id)===String(id));if(!c)return;for(const [k,v] of Object.entries(c)){const el=categoryForm.elements[k];if(!el)continue;if(el.type==='checkbox')el.checked=!!v;else el.value=v??''}categoryForm.elements.dbid.value=c.id;$('#category-title').textContent='Editar categoria';window.scrollTo({top:0,behavior:'smooth'});return}if(kind==='banner'){const b=(site.banners||[]).find(x=>String(x.id)===String(id));if(!b)return;for(const [k,v] of Object.entries(b)){const el=bannerForm.elements[k];if(!el)continue;if(el.type==='checkbox')el.checked=!!v;else el.value=v??''}bannerForm.elements.dbid.value=b.id;$('#banner-title').textContent='Editar banner';window.scrollTo({top:0,behavior:'smooth'})}}
async function handleDelete(kind,id){if(kind==='item'){const r=rows.find(x=>String(x.id)===String(id));if(!r||!confirm(`Excluir “${r.dados?.nome}”?`))return;await api('/api/catalog',{method:'DELETE',body:JSON.stringify({id:r.id})});await load();return}const resource=kind==='category'?'categoria':'banner';const arr=kind==='category'?site.categorias:site.banners;const x=(arr||[]).find(v=>String(v.id)===String(id));if(!x||!confirm(`Excluir “${x.nome||x.titulo}”?`))return;await api('/api/site-admin',{method:'DELETE',body:JSON.stringify({resource,id:x.id})});await load()}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-edit],[data-del]');if(!btn)return;const kind=btn.dataset.kind,id=btn.dataset.edit||btn.dataset.del;if(btn.dataset.edit)handleEdit(kind,id);else handleDelete(kind,id).catch(err=>{if(/Não autorizado/i.test(err.message))location.replace('/admin/');else alert(err.message)})});
load();